development:
  adapter: postgresql
  database: openvoice2_development
  username: openvoice2
  password: letmein

test: &test
  adapter: postgresql
  database: openvoice2_test
  username: openvoice2
  password: letmein

cucumber:
  <<: *test